/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Entity, Index, JoinColumn, Column, PrimaryColumn, ManyToOne } from 'typeorm';
import { id } from './util/id.js';
import { MiAgentSession } from './AgentSession.js';
import type { MiAgentDialogueStyle } from './AgentDialogueStyle.js';
import type { MiDriveFile } from './DriveFile.js';

export const agentMessageRoles = ['user', 'assistant', 'system'] as const;
export type AgentMessageRole = typeof agentMessageRoles[number];

@Entity('agent_message')
@Index(['sessionId', 'createdAt'])
@Index('IDX_agent_message_session_client_request_role', ['sessionId', 'clientRequestId', 'role'], {
	unique: true,
	where: '"clientRequestId" IS NOT NULL',
})
export class MiAgentMessage {
	@PrimaryColumn(id())
	public id: string;

	@Column('timestamp with time zone')
	public createdAt: Date;

	@Index()
	@Column({
		...id(),
	})
	public sessionId: MiAgentSession['id'];

	@ManyToOne(() => MiAgentSession, {
		onDelete: 'CASCADE',
	})
	@JoinColumn()
	public session: MiAgentSession | null;

	@Column('varchar', {
		length: 32,
	})
	public role: AgentMessageRole;

	@Column('text')
	public content: string;

	/** Optional image attached by the user. The Drive file remains owned by the user. */
	@Column({
		...id(),
		nullable: true,
	})
	public imageFileId: MiDriveFile['id'] | null;

	/** Server-only result of the single recognition request for an attached image. */
	@Column('varchar', {
		length: 16,
		nullable: true,
	})
	public imageRecognitionStatus: 'succeeded' | 'failed' | null;

	@Column('text', {
		nullable: true,
	})
	public imageRecognitionDescription: string | null;

	/** Original assistant output. It is used by the edit view and private LLM history. */
	@Column('text', {
		nullable: true,
	})
	public rawContent: string | null;

	/** Exact model-generated proactive schedule control fragment, never returned by timeline APIs. */
	@Column('text', {
		nullable: true,
	})
	public proactiveScheduleControlRaw: string | null;

	/** Private server validation failure appended for the model on a later turn. */
	@Column('jsonb', {
		nullable: true,
	})
	public proactiveScheduleControlError: { code: string; message: string; processedAt: string } | null;

	/** Internal server-triggered turns participate in context but are hidden from normal chat views. */
	@Column('boolean', {
		default: false,
	})
	public isInternal: boolean;

	/**
	 * Stable ID generated by the client for one send operation.
	 * Stored on both messages so retried POSTs can reuse the original result.
	 */
	@Column('varchar', {
		length: 64,
		nullable: true,
	})
	public clientRequestId: string | null;

	/** 送信時点の会話スタイル（広場のスタイル別統計用；セッション側の切り替え後も保持） */
	@Column({
		...id(),
		nullable: true,
	})
	public statsDialogueStyleId: MiAgentDialogueStyle['id'] | null;

	@Column('integer', {
		nullable: true,
	})
	public promptTokens: number | null;

	@Column('integer', {
		nullable: true,
	})
	public completionTokens: number | null;
}
