/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Entity, Index, JoinColumn, Column, PrimaryColumn, ManyToOne } from 'typeorm';
import { id } from './util/id.js';
import { MiAgentSession } from './AgentSession.js';
import type { MiAgentDialogueStyle } from './AgentDialogueStyle.js';

export const agentMessageRoles = ['user', 'assistant', 'system'] as const;
export type AgentMessageRole = typeof agentMessageRoles[number];

@Entity('agent_message')
@Index(['sessionId', 'createdAt'])
@Index('IDX_agent_message_session_client_request_role', ['sessionId', 'clientRequestId', 'role'], {
	unique: true,
	where: '"clientRequestId" IS NOT NULL',
})
export class MiAgentMessage {
	@PrimaryColumn(id())
	public id: string;

	@Column('timestamp with time zone')
	public createdAt: Date;

	@Index()
	@Column({
		...id(),
	})
	public sessionId: MiAgentSession['id'];

	@ManyToOne(() => MiAgentSession, {
		onDelete: 'CASCADE',
	})
	@JoinColumn()
	public session: MiAgentSession | null;

	@Column('varchar', {
		length: 32,
	})
	public role: AgentMessageRole;

	@Column('text')
	public content: string;

	/**
	 * Stable ID generated by the client for one send operation.
	 * Stored on both messages so retried POSTs can reuse the original result.
	 */
	@Column('varchar', {
		length: 64,
		nullable: true,
	})
	public clientRequestId: string | null;

	/** 送信時点の会話スタイル（広場のスタイル別統計用；セッション側の切り替え後も保持） */
	@Column({
		...id(),
		nullable: true,
	})
	public statsDialogueStyleId: MiAgentDialogueStyle['id'] | null;

	@Column('integer', {
		nullable: true,
	})
	public promptTokens: number | null;

	@Column('integer', {
		nullable: true,
	})
	public completionTokens: number | null;
}
